### ISSUE TITLE
How to fix the all files in project dir?

### ISSUE THREAD

**Issue by kmvan** [makao/vscode-phpcsfixer#2]
I know "fix this file" can fix current file, then how to fix the all files in project dir?

Thank you. Great vsc ext.

**Comment by makao** [comment]
AFAIK there wasn't any option to fix all files in project dir. But you can still use CLI to fix all files in directory. Please refer to the readme on [PHP CS Fixer repo](https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/1.13)

Note this extension only works with v1 of PHP CS Fixer.
